[package]
name = "acp-debugger"
description = "A desktop debugger for the Agent Client Protocol (ACP)"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
